name: hunger-games
version: '${project.version}'
main: org.murilonerdx.Hungergames
api-version: '1.20'
commands:
  startgame:
    usage: /startgame
    description: Iniciar jogos mortais
    permission: hungergames.startgame
  hard-reset:
    usage: /hard-reset
    description: Reiniciar jogos mortais
    permission: hungergames.hard-reset
  enter-start:
    usage: /enter-start
    description: Iniciar entradas
    permission: hungergames.enter-start
  herobrine:
    usage: /herobrine
    description: Você vira o herobrine
    permission: hungergames.herobrine
  enter:
    description: Entrar no jogo de jogos mortais
    usage: /enter
  punish:
    description: Fazer jogador voltar a jogar
    usage: /punish <player> <zombies/light/spawn-creatures>
    permission: hungergames.enter
  pause:
    description: Pausar o jogo caso algo aconteça
    usage: /pause <player> <motive>
    permission: hungergames.pause
  continue:
    description: Continuar
    usage: /continue
    permission: hungergames.pause
permissions:
  hungergames.startgame:
    description: Você inicia os jogos mortais
    default: op
  hungergames.enter-start:
    description: Você inicia os jogos mortais
    default: op
  hungergames.pause:
    description: Pausar jogo
    default: op
  hungergames.herobrine:
    description: Você virou o herobrine
    default: op